In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [19]:
import numpy as np


In [4]:
list_1=[1,2,3,4,5]
result=np.array(list_1)
print(result)

[1 2 3 4 5]


In [5]:
type(result)


numpy.ndarray

jgjgjh

In [6]:
type(list_1)

list

In [8]:
list_2d=[[1,2,3],[4,5,6]]
array_2d=np.array(list_2d)
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [9]:
type(list_2d)

list

In [10]:
type(array_2d)

numpy.ndarray

In [11]:
tuple_1=(1,2,3,4)
array_tuple=np.array(tuple_1)
print(array_tuple)

[1 2 3 4]


In [12]:
type(tuple_1)

tuple

In [13]:
type(array_tuple)

numpy.ndarray

In [ ]:
arry_11=np.zeros((2,3))    #Arrays of Zeros, Ones, and Empty Arrays
arry_11

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arry_1=np.ones((2,3))      #Arrays of Zeros, Ones, and Empty Arrays
arry_1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arry_2=np.empty((2,3))      #Arrays of Zeros, Ones, and Empty Arrays
arry_2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr_linspace = np.linspace(0, 10, 5) # Start, Stop (inclusive), Numberof elements  Arrays with a Range of Numbers (arange, linspace)
arr_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
arr_range=np.arange(0,10,2)# Start, Stop (exclusive), Step   Arrays with a Range of Numbers (arange, linspace)
arr_range

array([0, 2, 4, 6, 8])

In [39]:
arr_linespace=np.linspace(0,20,5)
arr_linespace

array([ 0.,  5., 10., 15., 20.])

In [ ]:
# Random Number Arrays

rand_array_uniform=np.random.rand(3,2)    # Random numbers between 0 and 1 (uniform distribution)
rand_array_uniform

array([[0.94504307, 0.44935245],
       [0.47532392, 0.54826221],
       [0.18971018, 0.29659304]])

In [ ]:
# Random integers within a specified range

rand_array_int=np.random.randint(1,10, size=(2,3))
rand_array_int

array([[3, 9, 1],
       [1, 5, 1]], dtype=int32)

In [44]:
rand_array_uniform=np.random.rand(2,3)
rand_array_uniform

array([[0.46524618, 0.26380978, 0.80303047],
       [0.26299531, 0.17427768, 0.60415595]])

In [46]:
rand_array_int=np.random.randint(1,10,size=(3,2))
rand_array_int

array([[5, 6],
       [1, 1],
       [6, 2]], dtype=int32)

In [54]:
# 4.2 Array Attributes

arr=np.array([[1,2,3],[4,5,6]])
arr
arr.shape               #●.shape: Tuple representing the dimensions of the array.
                        # ● .ndim: Number of dimensions (axes) of the array.
                        #● .size: Total number of elements in the array.
                        #● .dtype: Data type of the elements in the array.
arr.ndim
arr.size
arr.dtype


dtype('int64')

In [ ]:
arr=np.array([1.5,2.5,3.2])
arr.dtype

dtype('float64')

In [ ]:
# 5.1 1D Array Indexing and Slicing
# 5.1 1D Array Indexing and Slicing

array_1=np.arange(10)
array_1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Accessing a single element
print("Elment at index 3",array_1[3])


Elment at index 3 3


In [59]:
# Slicing
print("Element from index 2 to 7 (exclusive)",array_1[2:7])


Element from index 2 to 7 (exclusive) [2 3 4 5 6]


In [61]:
print("Element from start to index 5 to end",array_1[:5])


Element from start to index 5 to end [0 1 2 3 4]


In [62]:
print("Element index 5 to end ",array_1[5:])

Element index 5 to end  [5 6 7 8 9]


In [63]:
print("Element with a step 2",array_1[: :2])

Element with a step 2 [0 2 4 6 8]


In [64]:
print("reverse array: ",array_1[::-1])

reverse array:  [9 8 7 6 5 4 3 2 1 0]
