In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np


In [4]:
list_1=[1,2,3,4]
result=np.array(list_1)
print(result)

[1 2 3 4]


In [5]:
type(result)

numpy.ndarray

In [6]:
type(list_1)

list

In [7]:
tuple_1=(1,2,3,4)
result=np.array(tuple_1)
print(result)

[1 2 3 4]


In [8]:
type(result)

numpy.ndarray

In [9]:
type(tuple_1)

tuple

In [10]:
list_2d=[[1,2,3],[4,5,6]]
result=np.array(list_2d)
print(result)

[[1 2 3]
 [4 5 6]]


In [11]:
type(result)

numpy.ndarray

In [12]:
type(list_2d)

list

In [14]:
array_0=np.zeros((2,3))
array_0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:

array_1=np.ones((3,5))
array_1


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
array_2=np.empty((2,3))
array_2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:

array_3=np.arange(0,10,2)
array_3

array([0, 2, 4, 6, 8])

In [24]:
array_4=np.linspace(0,10,5)
array_4

array([ 0. ,  2.5,  5. ,  7.5, 10. ])