In [2]:
import numpy as np


In [4]:
list_1=([1,2,3,4])
result=np.array(list_1)
print(type(list_1))
print(type(result))


<class 'list'>
<class 'numpy.ndarray'>


In [5]:
list_2D=([[1,2,3],[4,5,6]])
result=np.array(list_2D)
print(result)
print(type(list_2D))
print(type(result))

[[1 2 3]
 [4 5 6]]
<class 'list'>
<class 'numpy.ndarray'>


In [6]:
tuple=(1,2,3)
result=np.array(tuple)
print(result)
print(type(result))
print(type(tuple))

[1 2 3]
<class 'numpy.ndarray'>
<class 'tuple'>


In [ ]:
#arrays of zeros ones and empty arrays
#1. zeros
array_1=np.zeros((3,4))
array_1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#2. Ones
array_2=np.ones((3,4))
array_2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
#3.Empty
array_3=np.empty((3,4))
array_3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#Arrays with aRange of Numbers (arange,linespace)
#1.arange
arra_4=np.arange(10)
array_4=np.arange(0,10,2)
arr_4=np.arange(1,10,1)
print(arra_4)
print(array_4)
print(arr_4)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 2 3 4 5 6 7 8 9]


In [17]:
#2.linespace
array_5=np.linspace(0,10,5)
arra_5=np.linspace(1,15,3)
print(array_5)
print(arra_5)

[ 0.   2.5  5.   7.5 10. ]
[ 1.  8. 15.]


In [ ]:
#random number arrays
#1.Rand
array_6=np.random.rand(2,3)
print(array_6)

[[0.2482332  0.05990711 0.96455477]
 [0.77723179 0.47702297 0.73294547]]


In [23]:
#2 randint
array_7=np.random.randint(10,size=(2,3))
print(array_7)

[[0 3 6]
 [0 4 8]]


In [26]:
#array attributes
# 1. shape
array_8=np.array([[1,2,3],[4,5,6]])
print(array_8)
print("Shape of array : ",array_8.shape)


[[1 2 3]
 [4 5 6]]
Shape of array :  (2, 3)


In [ ]:
#2.ndim
arr_8=np.array([1,2,3,4])
print("Dimensinal of arrays : ",arr_8.ndim) # this is the one dimensional array
print("dimensional of array :",array_8.ndim) # this is the two dimensional array

Dimensinal of arrays :  1
dimensional of array : 2


In [ ]:
#3.dtype
print("datatype od arrays :",array_8.dtype) #integers datatype

datatype od arrays : int64


In [31]:
#4.size
print("size of arrays : ",array_8.size) #6 elements in this arrays

size of arrays :  6


In [43]:
#Arrays indexing and slicing
#1d array indexing and slicing
array_9=np.arange(1,11,1)
print("original array ",array_9)

#accessing a single element 
print("third element",array_9[3])
print("nineth element",array_9[9])

#slicing
print(array_9[1:6])
print(array_9[: :-1]) #reverse array
print(array_9[ : :2 ]) #stepping two
print(array_9[2:7])


original array  [ 1  2  3  4  5  6  7  8  9 10]
third element 4
nineth element 10
[2 3 4 5 6]
[10  9  8  7  6  5  4  3  2  1]
[1 3 5 7 9]
[3 4 5 6 7]


In [64]:
#2d arrays indexing and slicing
array__10=np.array([[25,26,27],[35,36,37],[45,46,47]])
print("original arrays \n ",array__10)

#access a single element (row 1,column2-remember0-indexing)
print(array__10[1,2]) # first row and second column
print(array__10[1,1])
print(array__10[2,2])

#accessing a entire row
print(array__10[2])

#accesing a entire column 
print(array__10[:,0])

#slicing rows and column
print(array__10[1:3,1:3])
print(array__10[1:3,:2])
print(array__10[1:3,1:])
print(array__10[1:3, ])
print(array__10[1:3,1])

original arrays 
  [[25 26 27]
 [35 36 37]
 [45 46 47]]
37
36
47
[45 46 47]
[25 35 45]
[[36 37]
 [46 47]]
[[35 36]
 [45 46]]
[[36 37]
 [46 47]]
[[35 36 37]
 [45 46 47]]
[36 46]


In [76]:
#boolean indexing
arr_1=np.array([11,22,33,44,55,66,22])
print("original arr",arr_1)
compare_value=22
print("compare the value ",arr_1==compare_value)

condition=arr_1>20
print("showing element greaater than 20 ",arr_1[condition])

print("Element divisible by 2 ",arr_1[arr_1%2==0])

original arr [11 22 33 44 55 66 22]
compare the value  [False  True False False False False  True]
showing element greaater than 20  [22 33 44 55 66 22]
Element divisible by 2  [22 44 66 22]


In [84]:
#fancy indexing
arr_2=np.arange(100,106)
print("original array",arr_2)

#fancy indexing on 1d array
indices=[1,4,5]
print(arr_2[indices])

#fancy indexing on 2d array
arra_2=np.random.randint(10,size=(3,3))
print(arra_2)

#select specific rows
row_to_select=[0,2]
print(arra_2[row_to_select]) #print 0th row and 2nd row

#select specific elements (pairs of rows,coulumn indices)
#(0,0),(1,2),(2,1)
print(arra_2[[0,1,2],[0,2,1]])

original array [100 101 102 103 104 105]
[101 104 105]
[[8 9 7]
 [1 8 9]
 [2 6 2]]
[[8 9 7]
 [2 6 2]]
[8 9 6]


In [96]:
#array manipulating 
 # 1. reshpaing
array_11=np.arange(1,13)
print("original array : " ,array_11)

#reshaping or converting to 1d array into 2D array
print(array_11.reshape(3,4))
print(array_11.reshape(2,-1)) #only converting two rows 

#flatten an array back to 1D
flattened_array=array_11.flatten()     #back karta hai 1d mein
print(flattened_array)



original array :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [106]:
#2.concatenation
ar_1=[[1,2],[3,4]]
ar_2=[[5,6],[7,8]]
print(ar_1)
print(ar_2)

#concatenate along axis =0(rows)
concatenate_rows=np.concatenate((ar_1,ar_2),axis=0)
print(concatenate_rows)

#conactenate along axis =1(column)
concatenate_column=np.concatenate((ar_1,ar_2),axis=1)
print(concatenate_column)

#vertical stack (vstack)
v_stacked=np.vstack((ar_1,ar_2))
print(v_stacked)    #ye vertically ya row vise print karega

h_stacked=np.hstack((ar_1,ar_2))
print(h_stacked)  #ye horizontaly ya column vise print karega

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
