In [58]:
import numpy as np

list_1=[1,2,3,4,5]
result=np.array(list_1)
print(result)

[1 2 3 4 5]


In [59]:
type(list_1)

list

In [60]:
type(result)

numpy.ndarray

In [61]:
tuple_1=(1,2,3,4,5)
resul=np.array(tuple_1)
print(resul)

[1 2 3 4 5]


In [62]:
type(tuple_1)

tuple

In [63]:
type(resul)

numpy.ndarray

In [64]:
list_2D=[[1,2,3],[4,5,6]]
re=np.array(list_2D)
print(re)

[[1 2 3]
 [4 5 6]]


In [65]:
type(list_2D)

list

In [66]:
type(re)

numpy.ndarray

In [67]:
#Arrays of Zeros, Ones, and Empty Arrays
array_0=np.zeros((2,3))
array_0



array([[0., 0., 0.],
       [0., 0., 0.]])

In [68]:
#Arrays of Zeros, Ones, and Empty Arrays
array_1=np.ones((2,3))
array_1


array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
#Arrays of Zeros, Ones, and Empty Arrays
array_2=np.empty((2,3))
array_2


array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
# Start, Stop (exclusive), Step   Arrays with a Range of Numbers (arange, linspace)
arr_arange=np.arange(0,11,2)
arr_arange


array([ 0,  2,  4,  6,  8, 10])

In [71]:
 # linespace Start, Stop (inclusive), Number of elements


arr_linspace=np.linspace(0,10,5)
arr_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [72]:
# Random Number Arrays
array_3=np.random.rand(2,3) #Random numbers between 0 and 1 (uniform distribution)
array_3


array([[0.95175357, 0.34904551, 0.62406998],
       [0.38782516, 0.44226358, 0.80267555]])

In [73]:
# Random Number Arrays

array_4=np.random.randint(1,10 ,size=(2,3))# Random integers within a specified range
array_4



array([[7, 7, 3],
       [9, 2, 3]], dtype=int32)

In [74]:
# 4.2 Array Attributes
array_5=np.array([[1,2,3],[4,5,6]])
array_5

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
array_5.shape      #●.shape: Tuple representing the dimensions of the arra

(2, 3)

In [76]:
array_5.dtype      #● .dtype: Data type of the elements in the array.

dtype('int64')

In [77]:
array_5.ndim        # ● .ndim: Number of dimensions (axes) of the array.

2

In [78]:
array_5.size         #.size: Total number of elements in the array.

6

In [79]:
#checking the datatype of the array
array_6=np.array([1.5,2.5,3.2])
array_6.dtype

dtype('float64')

In [80]:
# 5.1 1D Array Indexing and Slicing
array_7=np.arange(10)
array_7


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
# Accessing a single element
print("Elment at index 3",array_7[9])


Elment at index 3 9


In [82]:
# Slicing
print("Element from index 2 to 7 (exclusive)",array_7[2:7])



Element from index 2 to 7 (exclusive) [2 3 4 5 6]


In [83]:
print("Element from start to index 5 to end",array_7[:5])

Element from start to index 5 to end [0 1 2 3 4]


In [84]:
print("Element index 5 to end ",array_7[5: :])

Element index 5 to end  [5 6 7 8 9]


In [85]:
print("Element with a step 2",array_7[: :2])

Element with a step 2 [0 2 4 6 8]


In [86]:
print("reverse array: ",array_7[: :-1])

reverse array:  [9 8 7 6 5 4 3 2 1 0]


In [87]:

array_8=np.random.randint(1,10,size=(3,5))
array_8

array([[4, 1, 1, 5, 7],
       [3, 8, 9, 2, 6],
       [5, 9, 6, 7, 3]], dtype=int32)

In [88]:
print(array_8[2,3])   #indexing


7


In [89]:
print(array_8[1,4])#indexing

6


In [90]:
print(array_8[0,3])    #indexing

5


In [91]:
#slicing
print(array_8[0:2,2:4])

[[1 5]
 [9 2]]


In [92]:
print(array_8[ : ,2:4])#slicing

[[1 5]
 [9 2]
 [6 7]]


In [93]:
print(array_8[0:2, 0:4 ])    #slicing

[[4 1 1 5]
 [3 8 9 2]]


In [94]:
print(array_8[1:2, : ])    #slicing

[[3 8 9 2 6]]


In [95]:
print(array_8[ : ,3:4])   #slicing

[[5]
 [2]
 [7]]


In [96]:
# 5.3 Boolean Indexing 
arr_1=np.array([10,20,30,40,50,60,70])
print("Orginal Array :",arr_1)

Orginal Array : [10 20 30 40 50 60 70]


In [97]:
condition=arr_1>30
condition

array([False, False, False,  True,  True,  True,  True])

In [98]:
print(arr_1[condition])

[40 50 60 70]


In [99]:
print("elment directly divided by 20 : ",arr_1[arr_1%15==0])

elment directly divided by 20 :  [30 60]


In [100]:
# Boolean indexing on 2D array 
arr_2=np.random.randint(1,10,size=(3,3))
print("original 2d array:\n",arr_2)



original 2d array:
 [[6 8 7]
 [3 9 8]
 [1 8 5]]


In [101]:
print("elment >5 in 2d array :",arr_2[arr_2>5])

elment >5 in 2d array : [6 8 7 9 8 8]


In [102]:
# 5.4 Fancy Indexing
arr_3=np.arange(1,11)
arr_3



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
# 5.4 Fancy Indexing
indices=[7,9,2]
print(arr_3[indices])

[ 8 10  3]


In [104]:
# Fancy indexing on 2D array
arr_4=np.random.randint(10,20,size=(3,5))
arr_4



array([[19, 19, 16, 18, 16],
       [12, 15, 10, 15, 16],
       [12, 18, 15, 10, 13]], dtype=int32)

In [105]:
row_to_select=[0,2]
print(arr_4[row_to_select])  #extarct 0 and 2 row


[[19 19 16 18 16]
 [12 18 15 10 13]]


In [106]:
# Select specific elements (pairs of row, column indices)
# (0,0), (1,2), (2,1)
print("Selected specific elements:",arr_4[[1,0,1],[1,2,0]])
print("Selcted specific elements :", arr_4[[0,1,2],[3,3,3]])




Selected specific elements: [15 16 12]
Selcted specific elements : [18 15 10]


In [107]:
# 6. Array Manipulation 
# 6.1 Reshaping
arr_5=np.arange(1,13)
arr_5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [108]:
# Reshape to a 3x4 2D array
reshaped=arr_5.reshape(3,4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
reshaped_array_auto=arr_5.reshape(2,-1)    # 2 rows, columns inferred 
reshaped_array_auto


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [110]:
flattened_arr=reshaped.flatten()        # Flatten an array back to 1D 
flattened_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
#concatenation
ar_1=([[1,2],[3,4]])
ar_2=([[5,6],[7,8]])
print(ar_1)
print(ar_2)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]


In [112]:
concatenate_rows=np.concatenate((ar_1,ar_2),axis=1)
print(concatenate_rows)

[[1 2 5 6]
 [3 4 7 8]]


In [113]:
# Alternative: vstack (vertical stack) and hstack (horizontal stack)
v_stacked=np.vstack((ar_1,ar_2))
v_stacked



array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [114]:
# Alternative: vstack (vertical stack) and hstack (horizontal stack)

h_stacked=np.hstack((ar_1,ar_2))
h_stacked

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [115]:
#splitting
#Divide an array into mu;tiple subarrays

ar_3=np.arange(12).reshape(3,4)
ar_3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
# Split horizontally (columns) into 2 equal parts 
arr_splt_h=np.hsplit(ar_3,2)
print(arr_splt_h[0])


[[0 1]
 [4 5]
 [8 9]]


In [117]:
print(arr_splt_h[1])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [118]:
# Split vertically (rows) into 3 equal parts 
arr_split_v=np.vsplit(ar_3,3)
arr_split_v[0]

array([[0, 1, 2, 3]])

In [119]:
arr_split_v[1]

array([[4, 5, 6, 7]])

In [120]:
arr_split_v[2]

array([[ 8,  9, 10, 11]])

In [121]:
# 7.2 Broadcasting
arr = np.array([[1, 2, 3], 
[4, 5, 6]]) 
scalar = 10 
print("Array:\n", arr) 
print("Scalar:", scalar) 
# Add scalar to all elements 
print("\nArray + Scalar:\n", arr + scalar) 

Array:
 [[1 2 3]
 [4 5 6]]
Scalar: 10

Array + Scalar:
 [[11 12 13]
 [14 15 16]]


In [122]:
array_2d=np.array([[1,2,3],[4,5,6]])
arraY_1d=np.array([10,20,30])
print("array 1d +array 2d",arraY_1d+array_2d)

array 1d +array 2d [[11 22 33]
 [14 25 36]]


In [123]:
# 7.3 Comparison Operations
arr1 = np.array([10, 20, 30]) 
arr2 = np.array([15, 20, 25])

print(arr1==arr2)
print(arr1>arr2)
print(arr1<arr2)


[False  True False]
[False False  True]
[ True False False]


In [124]:
# 8. Aggregate Functions 
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("original array ",arr)

# Sum of all elements 
print("The sum of all element is ",np.sum(arr))




original array  [[1 2 3]
 [4 5 6]
 [7 8 9]]
The sum of all element is  45


In [125]:
# Sum along rows (axis=0, sums down columns) 
print("sum along axes=0(columns)",np.sum(arr,axis=0))  #row vise sum

sum along axes=0(columns) [12 15 18]


In [126]:
# Sum along columns (axis=1, sums across rows)
print("sum along axis=1(rows) ",np.sum(arr,axis=1))

sum along axis=1(rows)  [ 6 15 24]


In [127]:
# Other common aggregate functions: 
print("mean of all elememt is ",np.mean(arr))

mean of all elememt is  5.0


In [128]:
print("Min of all element is ",np.min(arr))

Min of all element is  1


In [129]:
print("max of all element is ",np.max(arr))

max of all element is  9


In [130]:
print("Standard deviation of all elements:",np.std(arr))

Standard deviation of all elements: 2.581988897471611


In [131]:
print("min along axis =0",np.min(arr,axis=0))
print("max along axis =1",np.max(arr,axis=1))

min along axis =0 [1 2 3]
max along axis =1 [3 6 9]


In [132]:
# argmin/argmax: Returns the index of the minimum/maximum value 
print("Index of min element in flattened array:", np.argmin(arr)) # 0 
#(index of 1) 
print("Index of max element along axis=0:", np.argmax(arr, axis=0)) 

Index of min element in flattened array: 0
Index of max element along axis=0: [2 2 2]


In [133]:
# 9. Linear Algebra 
# NumPy is excellent for linear algebra operations. The numpy.linalg module provides a wide 
# range of functions. 
# 9.1 Dot Product 
# The dot product of two arrays (vectors or matrices).
vec1=np.array([1,2])
vec2=np.array([3,4])
print("vec1:", vec1) 
print("vec2:", vec2)




vec1: [1 2]
vec2: [3 4]


In [134]:
# Dot product of two vectors 
dot_product=np.dot(vec1,vec2)
print("dot product of vectors : ",dot_product)

dot product of vectors :  11


In [135]:
mat1=([[1,2],[3,4]])
mat2=([[5,6,],[7,8]])
print("\nMat1:\n", mat1) 
print("Mat2:\n", mat2) 


Mat1:
 [[1, 2], [3, 4]]
Mat2:
 [[5, 6], [7, 8]]


In [136]:
# Matrix multiplication (dot product for matrices) 
# For matrix multiplication, both np.dot() and np.matmul() can be used
# but `@` operator is preferred for clarity since Python 3.5

matrix_mult=np.dot(mat1,mat2)
matrix_mult

array([[19, 22],
       [43, 50]])

In [137]:
# 9.2 Other Linear Algebra Functions (Brief) 
# Determinant of a matrix 
mat = np.array([[1, 2], [3, 4]]) 
# Determinant of a matrix 
det = np.linalg.det(mat) 
print("\nDeterminant of matrix:\n", det) # Output: -2.0 
# Inverse of a matrix 
try: 
inv_mat = np.linalg.inv(mat) 
print("Inverse of matrix:\n", inv_mat) 
# Output: 
# [[-2.   1. ] 
#  [ 1.5 -0.5]] 
except np.linalg.LinAlgError: 
print("Matrix is singular (no inverse).")

IndentationError: expected an indented block after 'try' statement on line 8 (3947852340.py, line 9)

In [138]:
# 10. File I/O 
# NumPy allows saving and loading arrays to/from disk.

# Create an array
data_to_save=np.arange(10).reshape(2,5)
data_to_save

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [139]:
# Save to a binary .npy file (NumPy's native format)
np.save('my_array.npy',data_to_save) 
print("\nArray saved to my_array.npy") 


Array saved to my_array.npy


In [140]:
# Load from a .npy file 
loaded_array = np.load('my_array.npy') 
print("Loaded array from my_array.npy:\n", loaded_array) 

Loaded array from my_array.npy:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [141]:
# Save to a text file (e.g., .txt or .csv) 
# Use fmt to specify format (e.g., '%.2f' for float with 2 decimal places) 

np.savetxt('my_array.txt', data_to_save, fmt='%d', delimiter=',') 
print("\nArray saved to my_array.txt (comma-separated integers)") 


Array saved to my_array.txt (comma-separated integers)


In [142]:
# Load from a text file 
loaded_from_txt = np.loadtxt('my_array.txt', delimiter=',') 
print("Loaded array from my_array.txt:\n", loaded_from_txt)

Loaded array from my_array.txt:
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
