In [3]:
import numpy as np

list_1=[1,2,3,4,5]
result=np.array(list_1)
print(result)

[1 2 3 4 5]


In [4]:
type(list_1)

list

In [5]:
type(result)

numpy.ndarray

In [ ]:
tuple_1=(1,2,3,4,5)
resul=np.array(tuple_1)
print(resul)

[1 2 3 4 5]


In [7]:
type(tuple_1)

tuple

In [8]:
type(resul)

numpy.ndarray

In [10]:
list_2D=[[1,2,3],[4,5,6]]
re=np.array(list_2D)
print(re)

[[1 2 3]
 [4 5 6]]


In [11]:
type(list_2D)

list

In [12]:
type(re)

numpy.ndarray

In [15]:
#Arrays of Zeros, Ones, and Empty Arrays
array_0=np.zeros((2,3))
array_0



array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#Arrays of Zeros, Ones, and Empty Arrays
array_1=np.ones((2,3))
array_1


array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#Arrays of Zeros, Ones, and Empty Arrays
array_2=np.empty((2,3))
array_2


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Start, Stop (exclusive), Step   Arrays with a Range of Numbers (arange, linspace)
arr_arange=np.arange(0,11,2)
arr_arange


array([ 0,  2,  4,  6,  8, 10])

In [ ]:
 # linespace Start, Stop (inclusive), Number of elements


arr_linspace=np.linspace(0,10,5)
arr_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# Random Number Arrays
array_3=np.random.rand(2,3) #Random numbers between 0 and 1 (uniform distribution)
array_3


array([[0.86277537, 0.02930769, 0.96892932],
       [0.90405277, 0.99378063, 0.44897575]])

In [ ]:
# Random Number Arrays

array_4=np.random.randint(1,10 ,size=(2,3))# Random integers within a specified range
array_4



array([[3, 7, 9],
       [9, 7, 6]], dtype=int32)

In [ ]:
# 4.2 Array Attributes
array_5=np.array([[1,2,3],[4,5,6]])
array_5

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_5.shape      #●.shape: Tuple representing the dimensions of the arra

(2, 3)

In [ ]:
array_5.dtype      #● .dtype: Data type of the elements in the array.

dtype('int64')

In [ ]:
array_5.ndim        # ● .ndim: Number of dimensions (axes) of the array.

2

In [ ]:
array_5.size         #.size: Total number of elements in the array.

6

In [ ]:
#checking the datatype of the array
array_6=np.array([1.5,2.5,3.2])
array_6.dtype

dtype('float64')

In [40]:
# 5.1 1D Array Indexing and Slicing
array_7=np.arange(10)
array_7


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Accessing a single element
print("Elment at index 3",array_7[9])


The seventh element is 9


In [44]:
# Slicing
print("Element from index 2 to 7 (exclusive)",array_7[2:7])



Element from index 2 to 7 (exclusive) [2 3 4 5 6]


In [45]:
print("Element from start to index 5 to end",array_7[:5])

Element from start to index 5 to end [0 1 2 3 4]


In [47]:
print("Element index 5 to end ",array_7[5: :])

Element index 5 to end  [5 6 7 8 9]


In [48]:
print("Element with a step 2",array_7[: :2])

Element with a step 2 [0 2 4 6 8]


In [50]:
print("reverse array: ",array_7[: :-1])

reverse array:  [9 8 7 6 5 4 3 2 1 0]
